from enum import Enum

# As defined at https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-5

    
class HandshakeType(Enum):
    HELLO_REQUEST = 0
    CLIENT_HELLO = 1
    SERVER_HELLO = 2
    HELLO_VERIFY_REQUEST_RESERVED = 3
    NEW_SESSION_TICKET = 4
    END_OF_EARLY_DATA = 5
    HELLO_RETRY_REQUEST = 6
    ENCRYPTED_EXTENSIONS = 8
    REQUEST_CONNECTION_ID = 9
    NEW_CONNECTION_ID = 10
    CERTIFICATE = 11
    SERVER_KEY_EXCHANGE = 12
    CERTIFICATE_REQUEST = 13
    SERVER_HELLO_DONE = 14
    CERTIFICATE_VERIFY = 15
    CLIENT_KEY_EXCHANGE = 16
    CLIENT_CERTIFICATE_REQUEST = 17
    FINISHED = 20
    CERTIFICATE_URL_RESERVED = 21
    CERTIFICATE_STATUS_RESERVED = 22
    SUPPLEMENTAL_DATA_RESERVED = 23
    KEY_UPDATE = 24
    COMPRESSED_CERTIFICATE = 25
    EKT_KEY = 26
    MESSAGE_HASH = 254
    